// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/chinmayb/gotunnel/pkg/pb/tunnel.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Send struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Send) Reset()         { *m = Send{} }
func (m *Send) String() string { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()    {}
func (*Send) Descriptor() ([]byte, []int) {
	return fileDescriptor_145acff6afb9d2ae, []int{0}
}

func (m *Send) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Send.Unmarshal(m, b)
}
func (m *Send) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Send.Marshal(b, m, deterministic)
}
func (m *Send) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Send.Merge(m, src)
}
func (m *Send) XXX_Size() int {
	return xxx_messageInfo_Send.Size(m)
}
func (m *Send) XXX_DiscardUnknown() {
	xxx_messageInfo_Send.DiscardUnknown(m)
}

var xxx_messageInfo_Send proto.InternalMessageInfo

func (m *Send) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Send) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Receive struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receive) Reset()         { *m = Receive{} }
func (m *Receive) String() string { return proto.CompactTextString(m) }
func (*Receive) ProtoMessage()    {}
func (*Receive) Descriptor() ([]byte, []int) {
	return fileDescriptor_145acff6afb9d2ae, []int{1}
}

func (m *Receive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receive.Unmarshal(m, b)
}
func (m *Receive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receive.Marshal(b, m, deterministic)
}
func (m *Receive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receive.Merge(m, src)
}
func (m *Receive) XXX_Size() int {
	return xxx_messageInfo_Receive.Size(m)
}
func (m *Receive) XXX_DiscardUnknown() {
	xxx_messageInfo_Receive.DiscardUnknown(m)
}

var xxx_messageInfo_Receive proto.InternalMessageInfo

func (m *Receive) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Receive) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Send)(nil), "tunnel.Send")
	proto.RegisterType((*Receive)(nil), "tunnel.Receive")
}

func init() {
	proto.RegisterFile("github.com/chinmayb/gotunnel/pkg/pb/tunnel.proto", fileDescriptor_145acff6afb9d2ae)
}

var fileDescriptor_145acff6afb9d2ae = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x3d, 0x4b, 0xc5, 0x30,
	0x18, 0x85, 0xcd, 0xf5, 0xd2, 0x8b, 0x51, 0x14, 0x82, 0xc3, 0xb5, 0x53, 0xe9, 0x62, 0x5c, 0x92,
	0x52, 0x17, 0xc1, 0x45, 0xed, 0x3f, 0xa8, 0x4e, 0x6e, 0xf9, 0x32, 0x0d, 0xb6, 0x6f, 0x82, 0xa4,
	0x42, 0xff, 0xbd, 0x98, 0xb4, 0xbb, 0x38, 0x3e, 0xe1, 0xf0, 0x9c, 0x93, 0x17, 0x37, 0xd6, 0xc5,
	0x61, 0x96, 0x4c, 0xf9, 0x89, 0xab, 0xc1, 0xc1, 0x24, 0x16, 0xc9, 0xad, 0x8f, 0x33, 0x80, 0x19,
	0x79, 0xf8, 0xb4, 0x3c, 0x48, 0x9e, 0x89, 0x85, 0x2f, 0x1f, 0x3d, 0x29, 0x32, 0x95, 0x37, 0xd6,
	0x7b, 0x3b, 0x1a, 0x9e, 0x5e, 0xe5, 0xfc, 0xc1, 0x05, 0x2c, 0x39, 0x52, 0x3f, 0xe1, 0xfd, 0xab,
	0x01, 0x4d, 0x2e, 0xf1, 0xce, 0xe9, 0x23, 0xaa, 0x10, 0x3d, 0xeb, 0x77, 0x4e, 0x13, 0x8a, 0xf7,
	0x5a, 0x44, 0x71, 0x3c, 0xad, 0x10, 0x3d, 0x6f, 0xaf, 0x59, 0x36, 0xb0, 0xcd, 0xc0, 0x9e, 0x61,
	0xe9, 0x53, 0xa2, 0xee, 0xf0, 0xa1, 0x37, 0xca, 0xb8, 0x6f, 0xf3, 0x7f, 0x49, 0xfb, 0x80, 0x8b,
	0xb7, 0xb4, 0x95, 0x30, 0x7c, 0xe8, 0x3c, 0x80, 0x51, 0x91, 0x5c, 0xb0, 0xf5, 0x37, 0xbf, 0x0b,
	0xcb, 0xab, 0x8d, 0xd6, 0xb6, 0xfa, 0x84, 0xa2, 0x06, 0xbd, 0xdc, 0xbd, 0xdf, 0xfe, 0xe5, 0x2e,
	0x8f, 0x41, 0xca, 0x22, 0x15, 0xdf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x4b, 0x6b, 0xb8,
	0x49, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TunnelClient is the client API for Tunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TunnelClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Tunnel_ConnectClient, error)
}

type tunnelClient struct {
	cc *grpc.ClientConn
}

func NewTunnelClient(cc *grpc.ClientConn) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Tunnel_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tunnel_serviceDesc.Streams[0], "/tunnel.Tunnel/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelConnectClient{stream}
	return x, nil
}

type Tunnel_ConnectClient interface {
	Send(*Send) error
	Recv() (*Receive, error)
	grpc.ClientStream
}

type tunnelConnectClient struct {
	grpc.ClientStream
}

func (x *tunnelConnectClient) Send(m *Send) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelConnectClient) Recv() (*Receive, error) {
	m := new(Receive)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServer is the server API for Tunnel service.
type TunnelServer interface {
	Connect(Tunnel_ConnectServer) error
}

func RegisterTunnelServer(s *grpc.Server, srv TunnelServer) {
	s.RegisterService(&_Tunnel_serviceDesc, srv)
}

func _Tunnel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).Connect(&tunnelConnectServer{stream})
}

type Tunnel_ConnectServer interface {
	Send(*Receive) error
	Recv() (*Send, error)
	grpc.ServerStream
}

type tunnelConnectServer struct {
	grpc.ServerStream
}

func (x *tunnelConnectServer) Send(m *Receive) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelConnectServer) Recv() (*Send, error) {
	m := new(Send)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Tunnel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Tunnel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/chinmayb/gotunnel/pkg/pb/tunnel.proto",
}
